version: '2.3'

services:
  app:
    image: app
    runtime: nvidia
    pid: "host"
    ports:
      - 5010:5000
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
    command: waitress-serve --port=5000 backend:app # команда для поднятия сервиса с моделями

  dash:
   image: dash
   runtime: nvidia
   pid: "host"
   ports:
     - 5011:5000
   stdin_open: true
   tty: true
   volumes:
     - .:/workspace/dash
   build:
     context: .
     network: host
     dockerfile: ./Dockerfile
   command: python ./dash/app.py # команда для поднятия фронта на dash'е


volumes:
  app:
  dash: